spring.application.name=argos-orders
 # ==========================
# DATASOURCE (PostgreSQL)
# ==========================
spring.datasource.url=jdbc:postgresql://localhost:5432/flashsale_db
spring.datasource.username=user_flashsale
spring.datasource.password=password_flashsale
spring.datasource.driver-class-name=org.hibernate.dialect.PostgreSQLDialect
# Importante para que Hibernate entienda Postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Mantener la sincronización que logramos antes
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
#spring.rabbitmq.listener.simple.prefetch=1