spring.application.name=argos-sentinel
# ==========================
# RABBITMQ
# ==========================
spring.rabbitmq.host=message_broker
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin123
spring.threads.virtual.enabled=true
spring.rabbitmq.listener.simple.prefetch=1